apiVersion: v1
kind: Service
metadata:
  name: nubdb-nodeport
  namespace: nubdb
  labels:
    app: nubdb
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30379
    protocol: TCP
    name: nubdb
  selector:
    app: nubdb
